#! /bin/sh
#
# Maps reads to the original reference and the circularized reference.
# Splits the reads that span the end and start in the circularized reference
# and merges them with the reads that mapped to the original reference.


if [ $# -ne 3 ]; then
  echo "usage: circ_aln reference.fasta reads.fastq[.gz] prefix"
  exit 1
fi

ref=$1
fastq=$2
prefix=$3

# Align reads to both reference sequences
bwa mem ${ref} ${fastq} \
| samtools sort -T ${prefix}.lin -o ${prefix}.lin.s.bam -
samtools rmdup -s ${prefix}.lin.s.bam ${prefix}.lin.s.rd.bam

bwa mem ${ref}.circ.fa ${fastq} \
| samtools sort -T ${prefix}.circ -o ${prefix}.circ.s.bam -
samtools rmdup -s ${prefix}.circ.s.bam ${prefix}.circ.s.rd.bam

samtools index ${prefix}.circ.s.rd.bam

ref_len=$(grep '^>' -v ${ref} | tr -d '\n\t\r ' | wc -c)

circ_fix ${ref_len} ${prefix}.circ.s.rd.bam \
| samtools sort -T ${prefix}.circ.s.rd.fix -o ${prefix}.circ.s.rd.fix.s.bam


# Remove any alignments for our split reads.
samtools view ${prefix}.circ.s.rd.fix.s.bam \
| cut -f 1 \
> ${prefix}.split_qnames.txt

samtools view -h ${prefix}.lin.s.rd.bam \
| grep -v -F -f ${prefix}.split_qnames.txt \
| samtools view -b - > ${prefix}.lin.s.rd.rmfix.bam


# Merge the two files together
samtools merge -f ${prefix}.bam ${prefix}.lin.s.rd.rmfix.bam \
                                ${prefix}.circ.s.rd.fix.s.bam

#Clean up...
rm ${prefix}.circ* ${prefix}.lin* ${prefix}.split_qnames.txt
